/* CaresAgent 站点共享 EN 词典（每页中文从 DOM 自动抓取）。
   各页 <head> 先引 dict.js 设置 window.DEMO_EN，再内联 window.DEMO_EN_META（各页标题/描述），最后引 demo.js。 */
window.DEMO_EN = {
  /* —— 通用导航 / 页脚 —— */
  'nav.features': 'Capabilities',
  'nav.download': 'Download',
  'nav.cta': 'Download',
  'ft.product': 'Product',
  'ft.org': 'Institute',
  'ft.cair': 'CAIR website',
  'ft.dev': 'Contact the developer',
  'ft.contact': 'Address',
  'ft.addr': '3/F, Building 17W, Science Park West Avenue, Hong Kong Science Park, Pak Shek Kok, N.T., Hong Kong',
  'ft.copy': '© 2026 Centre for Artificial Intelligence and Robotics, HKISI-CAS.',
  'ft.rights': 'All rights reserved.',

  /* —— 首页 hero —— */
  'hero.eyebrow': 'Developed at CAIR · Hong Kong Institute of Science & Innovation, CAS',
  'hero.title': 'Cares AI<br /><em>agent system</em>',
  'hero.sub': 'It takes a task described in natural language, drafts its own plan, and executes it step by step with tools — files, terminal, browser — producing documents, slides and data analyses.',
  'hero.cta1': 'Download the desktop app',
  'hero.cta2': 'How to use it',
  'hero.meta': 'macOS · Windows · 简体中文 · English',

  /* —— 首页 app-window 实景（用语与桌面端语言包一致） —— */
  'shot.title': "Alzheimer's Imaging Study — CaresAgent",
  'shot.new': 'New conversation', 'shot.projects': 'Project',
  'shot.p1': "Alzheimer's Imaging Study", 'shot.p2': 'Surgical Robotics Review', 'shot.p3': 'Clinical Data Analysis',
  'shot.s1': 'Paper-to-PPT generation', 'shot.s2': 'Batch figure extraction',
  'shot.phone': 'Connect phone', 'shot.settings': 'Settings',
  'shot.user': 'Turn this PDF review into a 15-slide research deck — use the original figures from the paper.',
  'shot.proc': 'Processing', 'shot.st1': 'Read file · review_2026.pdf', 'shot.st2': 'Python code · extract_figures.py', 'shot.st3': 'Drafting slide outline…',
  'shot.ans': 'Figure selection complete: keeping Figure 2/4/7 and Table 1, all at presentation-ready resolution. The outline follows Background, Methods, Imaging findings, Conclusions…',
  'shot.ghost': 'Blow Figure 7 up to a full-page slide, then export a PDF version',
  'shot.ghostHint': 'Press Enter to send',
  'shot.railcap': 'Session info', 'shot.perms': 'Permissions', 'shot.pm1': 'Shell command · This project',
  'shot.plan': 'Plan', 'shot.pl1': 'Parse PDF structure', 'shot.pl2': 'Crop paper figures', 'shot.pl3': 'Outline & pagination', 'shot.pl4': 'Render PPTX',
  'shot.skills': 'Skills', 'shot.sk1': 'paper_ppt', 'shot.sk2': 'pdf_screenshot', 'shot.outputs': 'Outputs',

  /* —— 首页:概念 —— */
  'agent.eyebrow': 'Concept',
  'agent.title': 'What is <em>an agent</em>',
  'agent.sub': 'An agent is a software system built around a large language model: given a goal, it drafts a plan, executes it with tools and revises against the results until the task is done. Unlike a question-answering chat system, what it delivers is completed work and the files it produced, not a written answer.',
  'agent.s1t': 'Understand the goal', 'agent.s1d': 'A single natural-language instruction states the goal to be met.',
  'agent.s2t': 'Draft a plan', 'agent.s2d': 'The goal is broken into executable steps, adjusted as results come in.',
  'agent.s3t': 'Use tools', 'agent.s3d': 'Read and write files, run commands, operate the browser.',
  'agent.s4t': 'Check and complete', 'agent.s4d': 'Results are checked against the source files and data before a step is judged complete.',

  /* —— 首页:系统设计 —— */
  'design.eyebrow': 'System design',
  'design.title': 'Projects, sessions and <em>execution</em>',
  'design.sub': 'Work is organised in three layers — project, session, execution; the full mechanism is described under Architecture.',
  'design.t1': 'Project', 'design.d1': 'One working directory per research topic: literature, data and outputs all live inside it.',
  'design.t2': 'Session', 'design.d2': 'One session per task: the plan, the execution and the outputs are kept in full and can be reviewed at any time.',
  'design.t3': 'Execution', 'design.d3': 'The agent combines tools (files, terminal, browser) and skills (paper parsing, deck generation) to complete the task.',
  'design.more': 'Architecture →',

  /* —— 首页:使用 —— */
  'usage.eyebrow': 'Usage',
  'usage.title': 'How to <em>use it</em>',
  'usage.s1t': 'Download and install',
  'usage.s1d': 'Download the installer for your platform: on macOS drag the app into Applications, on Windows run the installer. This is a research preview; if macOS blocks the first launch, right-click the app and choose Open.',
  'usage.m1apps': 'Applications',
  'usage.s2t': 'Create or open a project',
  'usage.s2d': 'In the sidebar’s Projects menu, create a new empty project or open an existing folder as one; paper PDFs, scans and data files placed inside the project directory can be read from there. This is the only step required before you start.',
  'usage.s3t': 'Connect a model service',
  'usage.s3d': 'Under Settings → Model, enter the model endpoint, API key and model name — any OpenAI-compatible service will do, and changes apply instantly; a service run by your own institution also works.',
  'usage.s4t': 'Assign a task',
  'usage.s4d': 'State the goal in one sentence; the agent lays out a plan and executes step by step, with the process visible in the right-hand panel.',
  'usage.m4u': 'Turn this review into a 15-slide research deck — use the original figures from the paper.',
  'usage.m4p': 'Processing',
  'usage.m4s1': 'Read file · review_2026.pdf', 'usage.m4s2': 'Extracting original figures…', 'usage.m4s3': 'Create PowerPoint · slides_draft.pptx',
  'usage.s5t': 'Collect the results',
  'usage.s5d': 'Slides, reports and figures are written into the project directory and listed in the session’s output rail; the session is kept in full and every step can be reviewed.',
  'usage.m5n': 'Also written to the project directory · sessions can be reviewed in full',

  /* —— 首页:特点 —— */
  'wn.eyebrow': 'Interaction',
  'wn.title': 'Interaction between user <em>and agent</em>',
  'wn.sub': 'The terminal and the browser are shared between the user and the agent: execution stays visible, and the user can operate them directly at any time.',
  'wn.a.t': 'A shared terminal and browser',
  'wn.a.d': 'The terminal is one persistent zsh session — user and agent share the same prompt, and a command the agent has run can be followed up on. The browser is a native multi-tab window: while the agent operates a page, the user can click it. Both sit in the right-hand panel, which can be resized or maximised.',
  'wn.a.link': 'Capabilities →',
  'wn.a.note': '↑ One shared prompt: a command the agent has run can be followed up on',
  'wn.c.t': 'Choice cards',
  'wn.c.d': 'At a fork that needs the user to decide (outline structure, which figures to keep, which method to use), the agent pauses and lists the options in a card above the composer; execution continues once a choice is made, or a different answer can be typed in.',
  'wn.c.link': 'Architecture →',
  'wn.c.eyebrow': 'Choose the next step',
  'wn.c.cardt': 'Which structure should the deck follow?',
  'wn.c.b1': 'Background → Methods → Findings → Conclusions', 'wn.c.b2': 'One section per figure',
  'wn.c.free': 'Or type your own answer…', 'wn.c.submit': 'Submit answer',

  /* —— 首页:更新日志（已发布版本） —— */
  'log.eyebrow': 'Changelog',
  'log.title': 'Released <em>versions</em>',
  'log.add': 'New', 'log.imp': 'Better', 'log.first': 'First', 'log.fix': 'Fixed',
  'log.d13': 'August 2026',
  'log.i131': 'The app icon follows the light and dark themes \u2014 in dark mode the Dock shows its dark tile.',
  'log.i132': 'The terminal, the code buffer and the document page now open on one line, with matching margins, so switching pages no longer shifts the text.',
  'log.i133': 'The context meter has a new palette for its five bands, easier to tell apart in the light theme.',
  'log.i134': 'An applied update now announces itself in a banner under the title bar.',
  'log.d12': 'August 2026',
  'log.i121': 'Sessions can now be renamed.',
  'log.i122': 'Hover labels are now drawn by the app itself \u2014 one consistent bubble in both themes.',
  'log.i123': 'Error toasts now show the server\u2019s sentence directly, without its JSON wrapping.',
  'log.d11': 'August 2026',
  'log.i111': 'The message box has its thin outline back \u2014 subtle at rest, one step firmer while focused.',
  'log.d10': 'August 2026',
  'log.i101': 'The app reopens by itself once an update has been applied \u2014 no manual restart.',
  'log.i102': 'When a new version is ready, a \u201cRestart and update\u201d row appears at the foot of the sidebar; one click completes it.',
  'log.d9': 'August 2026',
  'log.i91': 'Automatic updates: \u201cQuit and update\u201d could appear too early, so quitting then installed nothing and said nothing. It now shows \u201cPreparing\u2026\u201d first and offers the action only once the update can truly be applied.',
  'log.d8': 'August 2026',
  'log.i81': 'The browser panel driver was rewritten: an action confirms at the moment it runs whether its target is visible and unobstructed, and navigation and load completion are judged more accurately.',
  'log.i82': 'Link icons are fetched through an in-app protocol that sends only the site\u2019s domain \u2014 page paths and query strings never leave the machine.',
  'log.i83': 'Interface-layer faults are now written to the same log as the backend, instead of vanishing with the toast that reported them.',
  'log.d7': 'August 2026',
  'log.i71': 'Formula cells in a workbook were read as their computed value and written back as the cell alone, which could silently corrupt formulas in someone else\u2019s spreadsheet.',
  'log.i72': 'File search no longer descends into hidden directories, so repository internals and the app\u2019s own state files stay out of the results.',
  'log.d6': 'August 2026',
  'log.i61': 'Automatic updates: a new version downloads in the background and installs when you quit the app, without interrupting your work.',
  'log.i62': 'The installer is signed and notarized by Apple, so opening it the first time no longer requires approving it in System Settings.',
  'log.i63': 'Spreadsheet values: thousands separators, percentages and currency, scientific notation and fractions are no longer stored as text.',
  'log.i64': 'Merged cells in scanned tables no longer shift columns, and image orientation follows the EXIF data.',
  'log.i65': 'A damaged settings file or index no longer prevents the app from starting.',
  'log.d5': 'August 2026',
  'log.i51': 'Reasoning models such as Qwen no longer leak their thinking into the visible answer.',
  'log.i52': 'Arguments to connected (MCP) tools are coerced to their declared types, so loosely-typed calls no longer fail.',
  'log.i53': 'Reasoning items are echoed back more robustly, avoiding rejected follow-up requests from some model services.',
  'log.d4': 'August 2026',
  'log.i41': 'Built-in editor: documents, spreadsheets, slides and PDFs open inside the application, where reading and editing happen on the same surface.',
  'log.i42': 'Block-level editing: Word, PowerPoint and Excel files are edited by paragraph, cell and slide, without rewriting the whole file.',
  'log.i43': 'Workspace file tree: the project directory is browsable in the panel, and any file in it opens directly.',
  'log.i44': 'Reading a file: its text can be read and its page layout examined, so scans and figures are presented as they are laid out.',
  'log.d3': 'August 2026',
  'log.i31': 'Memory: confirmed facts and a researcher\u2019s preferences carry across sessions, and can be read, edited and deleted from the interface.',
  'log.i32': 'Figures in the conversation: flowcharts and diagrams an answer draws are rendered in place, and can be copied or saved as SVG or PNG.',
  'log.i33': 'Tabs in the panels: the terminal and the browser each hold several tabs at once, with keyboard shortcuts to move between them.',
  'log.i34': 'Web operation: one call now carries a whole set of page actions, so a form is filled in a single step instead of one field per round trip.',
  'log.d2': 'August 2026',
  'log.i21': 'Scheduled tasks: sessions start automatically at the times you set, and their results land in the session record as usual.',
  'log.i22': 'Skill management: skill packages are added, edited and removed as whole packages from the interface, with no file editing.',
  'log.i23': 'Session timeline rebuilt: settled turns are no longer repainted, so long sessions scroll steadily.',
  'log.d1': 'June 2026',
  'log.i11': 'First public release: macOS and Windows desktop builds, with projects and sessions, tool calls, permission prompts and messaging channels.',
  'log.more': 'All versions and installers →',

  /* —— 核心特点页 —— */
  'cap.eyebrow': 'Core capabilities',
  'cap.title': 'Capabilities and <em>mechanisms</em>',
  'cap.stream.h': 'Process record',
  'cap.stream.h2': 'Processing',
  'cap.stream.n1': 'Let me parse the review’s section structure and figure positions first.',
  'cap.stream.t1': 'Open document · review_2026.pdf · 38 pages',
  'cap.stream.n2': 'Structure is clear — keeping Figure 2/4/7 + Table 1, rendering slides.',
  'cap.plan.h': 'Live plan rail',
  'cap.perm.h': 'Action confirmation',
  'cap.audit.h': 'The full session is kept',
  'cap.audit.d': 'Every tool call, decision and authorization is kept in full in the session record and can be reviewed at any time. See the Architecture page for the full mechanism.',
  'cap.audit.link': 'Architecture →',
  'perm.label': 'Send this WeChat message?', 'perm.wait': 'Waiting for approval', 'perm.btn': 'Allow once', 'perm.deny': 'Deny',
  'plan.s1': 'Parse PDF structure', 'plan.s2': 'Crop paper figures', 'plan.s3': 'Outline & pagination', 'plan.s4': 'Render PPTX', 'plan.s5': 'Quality checks',

  /* —— 消息渠道页 —— */
  'ch.title': 'Use it inside <em>the chat tools your team already uses</em>',
  'ch.sub': 'Connect WeChat, Feishu or WeCom: incoming messages become agent sessions, and outputs return over the same channel.',
  'ch.connect.d': 'Connect WeChat, Feishu or WeCom to CaresAgent: WeChat and Feishu connect by QR scan, WeCom by validating an AI-bot credential.',
  'ch.wc.h': 'WeChat', 'ch.fs.h': 'Feishu', 'ch.wm.h': 'WeCom', 'ch.matrix.h': 'Capabilities',
  'ch.matrix.sub': 'What each channel supports and does not support.',
  'm.col.feat': 'Capability', 'm.r1': 'Receive messages', 'm.r2': 'Reply in chat', 'm.r3': 'Hand files back', 'm.r4': 'Proactive outbound', 'm.r5': 'Group chat', 'm.r6': 'Identity',
  'm.yes': 'Yes', 'm.via': 'via Deliver file', 'm.wc.out': 'desktop only', 'm.wc.grp': 'named groups', 'm.id.bot': 'bot', 'm.id.app': 'app', 'm.id.aibot': 'AI bot', 'm.fs.grp': '@-mention', 'm.fs.out': 'reply-only', 'm.wm.out': 'semi-auto', 'm.wm.grp': 'internal + @',

  /* —— 下载页 —— */
  'dl.eyebrow': 'Download',
  'dl.title': 'Download <em>CaresAgent</em>',
  'dl.sub': 'Current version', 'dl.date': 'Released August 2026', 'dl.detected': 'Recommended for your system',
  'dl.macReq': 'macOS 12.0+, Apple silicon', 'dl.macBtn': 'Download DMG (Apple silicon)', 'dl.copy': 'Copy',
  'dl.winReq': 'Windows 10/11, x64', 'dl.winBtn': 'Download NSIS installer',
  'dl.linReq': 'x64, major distributions', 'dl.linBtn': 'Download AppImage',
  'dl.note': 'On first launch, connect a model service in Settings; the phone channel can be linked later via “Connect phone” at the bottom of the sidebar (optional).',

  /* —— 多页导航新增 —— */
  'nav.scenarios': 'Scenarios',
  'nav.arch': 'Architecture',
  'next.label': 'Learn more:',
  'cfg.model.title': 'Settings · Model — connect your own model',
  'cfg.model.l1': 'Model endpoint',
  'cfg.model.l3': 'Model name',
  'cfg.proj.title': 'Sidebar · Projects — create or open',
  'cfg.proj.new': 'New empty project',
  'cfg.proj.open': 'Open folder',

  /* —— 首页：场景导览 + 工作原则 —— */
  'home.scenes.eyebrow': 'Use it for',
  'home.scenes.title': 'A few <em>typical uses</em>',
  'home.enter': 'Details →',
  'sc.research.t': 'Research output', 'sc.research.d': 'Paper into research deck and data analysis; figures come from the paper itself, and results can be checked item by item.',
  'sc.office.t': 'Office automation', 'sc.office.d': 'Web tasks run in the shared browser, recorded with step-by-step screenshots; Official-Account articles are saved to the draft box before publishing.',
  'sc.channels.t': 'Messaging channels', 'sc.channels.d': 'Reach the agent from WeChat, Feishu or WeCom: assign tasks in your research group chat, and outputs return over the same channel.',
  'sc.ocr.t': 'Document parsing', 'sc.ocr.d': 'Literature, scans and PDF pages become structured Markdown: text in reading order, tables as HTML, formulas as LaTeX, figures cropped by layout.',

  /* —— 场景 · 科研产出 —— */
  'sr.eyebrow': 'Scenario · Research',
  'sr.title': 'A paper PDF <em>into a research deck</em>',
  'sr.lead': 'Import a PDF. The agent parses it, uses CL-OCR to read the text, tables and formulas and to crop the paper’s own figures by layout, then lays out a research deck — with the data analysis to back it up.',
  'sr.s1t': 'Import the paper', 'sr.s2t': 'Extract & verify', 'sr.s3t': 'Produce the results', 'sr.result': '<b>A 15-page deck and an analysis report:</b> every figure comes from the paper itself, and every metric notes its source and can be checked item by item.',

  /* —— 场景 · 自动化办公 —— */
  'so.eyebrow': 'Scenario · Office',
  'so.title': 'Browser flow tests and <em>Official-Account drafts</em>',
  'so.lead': 'Walk through a web flow with step-by-step screenshots, and draft an Official-Account post into the draft box.',
  'so.result': '<b>Step-by-step screenshot records</b>, and <b>a ready Official-Account draft</b> in your draft box.',

  /* —— 场景 · 消息渠道 —— */
  'sc2.eyebrow': 'Scenario · Channels',
  'sc2.result': '<b>Send and receive tasks in WeChat / Feishu / WeCom, with files returned over the same channel.</b>',

  /* —— 系统设计原理 —— */
  'arch.eyebrow': 'System design',
  'arch.title': 'Lifecycles and <em>the execution chain</em>',
  'arch.lead': 'Project, Session, Turn and Run each own clearly defined state. Inside a Run, the Agent combines context, Tools and Skills; Policy decides each call and Approval handles ask; typed Events project into the Timeline.',
  'arch.flow.title': 'From Project to Timeline',
  'arch.flow.sub': 'Project → Session → Turn → Run; inside the Run, an Agent combines context and Skills to call Tools, Policy evaluates each call as allow / ask / deny, Approval handles ask only, and typed Events project into the Timeline.',
  'arch.n.task': 'Project', 'arch.n.task2': 'workspace + config',
  'arch.n.context': 'Session', 'arch.n.context2': 'history + permissions',
  'arch.n.agent': 'Turn', 'arch.n.agent2': 'one user request',
  'arch.n.action': 'Run', 'arch.n.action2': 'one execution attempt',
  'arch.n.guard': 'Agent', 'arch.n.guard2': 'context + Skills',
  'arch.n.tool': 'Tool', 'arch.n.tool2': 'typed call',
  'arch.n.runtime': 'Policy', 'arch.n.runtime2': 'per-call decision',
  'arch.n.obs': 'Approval', 'arch.n.obs2': 'ask only',
  'arch.n.eval': 'Event', 'arch.n.eval2': 'typed fact',
  'arch.n.report': 'Timeline', 'arch.n.report2': 'deterministic projection',
  'arch.loop': 'A Run can block on ask, resume after approval or denial, or be cancelled; its settled state returns to the Session.',
  'arch.principles.title': 'Design rationale',
  'arch.p1t': 'Four explicit lifetimes', 'arch.p1d': 'Project owns workspace and configuration; Session owns durable conversation state; Turn maps to one user message; Run is one execution attempt that can block, resume or be cancelled.',
  'arch.p2t': 'Agent / Tool / Skill layering', 'arch.p2d': 'Agent reasons, Tool executes, and Skill supplies loadable instructions and resources; the three evolve and are tested independently.',
  'arch.p3t': 'Per-call Policy / Approval', 'arch.p3d': 'ToolDefinition, arguments, session mode and rules produce allow / ask / deny; only ask enters user approval and supports resumption.',
  'arch.p4t': 'Typed Event → Timeline', 'arch.p4d': 'The runtime emits typed <code>Event</code>s, appends them to the session log, then a deterministic reducer projects the <code>Timeline</code>; clients consume the projection instead of rebuilding domain decisions.',
  'arch.p5t': 'State and resources, separated', 'arch.p5d': 'Runtime data is stored in the application data directory; bundled configuration and Skills ship with the installer.',
  'arch.p6t': 'One API, multiple adapters', 'arch.p6d': 'caresagent.api.app:app is the only ASGI composition entry; desktop and messaging-channel adapters reuse the same application services, Policy and Event contracts.',
};
